name-template: '$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '💣 BREAKING CHANGES'
    labels:
      - 'BREAKING CHANGE'
  - title: '🌱 New Features'
    labels:
      - 'feature'
  - title: '✨ Improvements'
    labels:
      - 'improvement'
      - 'performance'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '✒ Documentation'
    labels:
      - 'doc'
  - title: '⬆️ Dependency Updates'
    labels:
      - 'deps'
exclude-labels:
  - 'chore'
  - 'no release note'
change-template: '- $TITLE (#$NUMBER)'
replacers:
  - search: '\b(:seedling:|🌱|:bug:|🐛|:sparkles:|✨|:black_nib:|✒️|:bomb:|💣|:arrow_up:|⬆️):\b'
    replace: ''
template: |
  ## Changes

  $CHANGES
