# DISABLED
#   Semantic Pull Request allows only ASCII characters(`\w` or `[a-zA-Z0-9_]`) for types.
#     https://github.com/tunnckoCoreLabs/parse-commit-message/blob/93018525c85296b44b41ddb7af1700afd5a54d60/src/header.js#L40

# About Conventional Commits
#   English: https://www.conventionalcommits.org/en/v1.0.0/
#   日本語: https://www.conventionalcommits.org/ja/v1.0.0/

# Always validate the PR title, and ignore the commits
titleOnly: true
# You can define a list of valid scopes
scopes:
  - deps
  - starter
  - autoconfig
  - core
  - typed-value
  - http-client
# By default types specified in commitizen/conventional-commit-types is used.
# See: https://github.com/commitizen/conventional-commit-types/blob/v2.2.0/index.json
# You can override the valid types
types:
  # A new feature. (feat)
  - ':seedling:'
  - '🌱'
  # A bug fix. (fix)
  - ':bug:'
  - '🐛'
  # An improvement to a current feature. (improvement)
  - ':sparkles:'
  - '✨'
  # Documentation only changes. (docs)
  - ':black_nib:'
  - '✒️'
  # Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc). (style)
  - ':art:'
  - '🎨'
  # A code change that neither fixes a bug nor adds a feature. (refactor)
  - ':recycle:'
  - '♻️'
  # A code change that improves performance. (perf)
  - ':zap:'
  - '⚡️'
  # Adding missing tests or correcting existing tests. (test)
  - ':white_check_mark:'
  - '✅'
  # Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm). (build)
  - ':hammer_and_pick:'
  - '⚒️'
  # Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs). (ci)
  - ':chart_with_upwards_trend:'
  - '📈'
  # Other changes that don't modify src or test files. (chore)
  - ':memo:'
  - '📝'
  # Reverts a previous commit. (revert)
  - ':rewind:'
  - '⏪'
  # Breaking change.
  - ':bomb:'
  - '💣'
  # Bump dependency version.
  - ':arrow_up:'
  - '⬆️'
  # Release
  - ':tada:'
  - '🎉'
# Allow use of Merge commits (eg on github: "Merge branch 'master' into feature/ride-unicorns")
# this is only relevant when using commitsOnly: true (or titleAndCommits: true)
allowMergeCommits: true
