repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: selidor

  # A short description of the repository that will show up on GitHub
  #  description: description of repo

  # A URL with more information about the repository
  #  homepage: https://example.github.io/

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: false

# Labels: define labels for Issues and Pull Requests
labels:
  - name: feature
    description: A new feature.
    color: 84b6eb
  - name: bug
    description: A bug fix.
    color: ee0701
  - name: improvement
    description: An improvement to a current feature.
    color: 9ff1fc
  - name: doc
    description: Documentation only changes.
    color: d4c5f9
  - name: chore
    description: Other changes that don't modify src or test files.
    color: fef2c0
  - name: performance
    description: A code change that improves performance.
    color: bcf5db
  - name: BREAKING_CHANGE
    description: Breaking change.
    color: 000000
  - name: deps
    description: Bump dependency version.
    color: bfe5bf
  - name: duplicate
    description: This issue or pull request already exists.
    color: eeeeee
  - name: good first issue
    description: Good for newcomers.
    color: 7057ff
  - name: help wanted
    description: Extra attention is needed.
    color: 0e8a16
  - name: invalid
    description: This doesn't seem right.
    color: eeeeee
  - name: question
    description: Further information is requested.
    color: cc317c
  - name: wip
    description: Work In Progress.
    color: eeeeee
  - name: wontfix
    description: This will not be worked on.
    color: ffffff
#  - name: first-timers-only
#    # include the old name to rename and existing label
#    oldname: Help Wanted

# Collaborators: give specific users access to this repository.
collaborators: []
