version: 1
issues:
  trackerName: GitHub
  serverID: artifactory-server
  regexp: (.+)\s+\(#([0-9]+)\)
  keyGroupIndex: 2
  summaryGroupIndex: 1
  trackerUrl: https://github.com/ryotan/selidor/issues/
  aggregate: true
  aggregationStatus: RELEASED
